---
kind: pipeline
type: exec
name: fermium

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone --depth 1 $DRONE_GIT_SSH_URL
- name: build
  commands:
  - cd $DRONE_REPO_NAME && echo $GIT_SUDO | sudo -S make && echo $GIT_SUDO | sudo -S make install
  environment:
    GIT_SUDO:
      from_secret: git_sudo

node:
  machine: fermium

---
kind: pipeline
type: exec
name: report

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: report
  commands:
  - /usr/local/bin/telegram.run

trigger:
  status:
  - success
  - failure

node:
  machine: hangar.rcmd.space

depends_on:
- fermium
